-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 08:36:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baseflights
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baseflights` ;

-- -----------------------------------------------------
-- Schema baseflights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseflights` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `baseflights` ;

-- -----------------------------------------------------
-- Table `baseflights`.`cashiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`cashiers` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`cashiers` (
  `id_cashier` INT NOT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cashier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`flightsstart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`flightsstart` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`flightsstart` (
  `id_flight` INT NOT NULL,
  `id_city` INT NULL DEFAULT NULL,
  `day_week` INT NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_flight`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`cities` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`cities` (
  `id_city` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `flightsstart_id_flight` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `fk_cities_flightsstart1_idx` (`flightsstart_id_flight` ASC) VISIBLE,
  CONSTRAINT `fk_cities_flightsstart1`
    FOREIGN KEY (`flightsstart_id_flight`)
    REFERENCES `baseflights`.`flightsstart` (`id_flight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`usersflight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`usersflight` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`usersflight` (
  `id` INT NOT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `id_flight` INT NULL DEFAULT NULL,
  `id_cashier` INT NULL DEFAULT NULL,
  `date_time_start` DATETIME NULL DEFAULT NULL,
  `date_time_end` DATETIME NULL DEFAULT NULL,
  `paid` BIT(1) NULL DEFAULT NULL,
  `cashiers_id_cashier` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usersflight_cashiers1_idx` (`cashiers_id_cashier` ASC) VISIBLE,
  CONSTRAINT `fk_usersflight_cashiers1`
    FOREIGN KEY (`cashiers_id_cashier`)
    REFERENCES `baseflights`.`cashiers` (`id_cashier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`flightsend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`flightsend` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`flightsend` (
  `id_flight` INT NOT NULL AUTO_INCREMENT,
  `day_week` INT NULL DEFAULT NULL,
  `id_city` INT NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `cities_id_city` INT NOT NULL,
  PRIMARY KEY (`id_flight`),
  INDEX `fk_flightsend_cities1_idx` (`cities_id_city` ASC) VISIBLE,
  CONSTRAINT `fk_flightsend_cities1`
    FOREIGN KEY (`cities_id_city`)
    REFERENCES `baseflights`.`cities` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`flights` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`flights` (
  `id_flight` INT NOT NULL,
  `number` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `places` INT NULL DEFAULT NULL,
  `usersflight_id` INT NOT NULL,
  `flightsend_id_flight` INT NOT NULL,
  `flightsstart_id_flight` INT NOT NULL,
  PRIMARY KEY (`id_flight`),
  INDEX `fk_flights_usersflight1_idx` (`usersflight_id` ASC) VISIBLE,
  INDEX `fk_flights_flightsend1_idx` (`flightsend_id_flight` ASC) VISIBLE,
  INDEX `fk_flights_flightsstart1_idx` (`flightsstart_id_flight` ASC) VISIBLE,
  CONSTRAINT `fk_flights_usersflight1`
    FOREIGN KEY (`usersflight_id`)
    REFERENCES `baseflights`.`usersflight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_flightsend1`
    FOREIGN KEY (`flightsend_id_flight`)
    REFERENCES `baseflights`.`flightsend` (`id_flight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_flightsstart1`
    FOREIGN KEY (`flightsstart_id_flight`)
    REFERENCES `baseflights`.`flightsstart` (`id_flight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baseflights`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseflights`.`users` ;

CREATE TABLE IF NOT EXISTS `baseflights`.`users` (
  `id_user` INT NOT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `serial_passport` VARCHAR(45) NULL DEFAULT NULL,
  `number_passport` VARCHAR(45) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `index_address` VARCHAR(45) NULL DEFAULT NULL,
  `region_address` VARCHAR(45) NULL DEFAULT NULL,
  `city_address` VARCHAR(45) NULL DEFAULT NULL,
  `street_address` VARCHAR(45) NULL DEFAULT NULL,
  `number_home_address` VARCHAR(45) NULL DEFAULT NULL,
  `number_appartment_address` VARCHAR(45) NULL DEFAULT NULL,
  `usersflight_id` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_usersflight_idx` (`usersflight_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_usersflight`
    FOREIGN KEY (`usersflight_id`)
    REFERENCES `baseflights`.`usersflight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
